# Site settings
url: http://jgkim.github.io
baseurl: /5stardata.info

# Translated Languages
languages:
  -
    - en
    - English
  -
    - ko
    - 한국어

# Plug-ins
gems:
  - jekyll-redirect-from

# Conversion
markdown: kramdown

# Outputting
permalink: pretty
timezone: GMT
