# Site settings
url: http://5stardata.info
baseurl: ""

# Translated Languages
languages:
  -
    - en
    - English
  -
    - es
    - Español
  -
    - ja
    - 日本語
  -
    - ko
    - 한국어

# Plug-ins
gems:
  - jekyll-redirect-from

# Conversion
markdown: kramdown

# Outputting
permalink: pretty
timezone: GMT
