# Site settings
url: http://5stardata.info
baseurl: ""

# Translated Languages
languages:
  -
    - en
    - English
  -
    - es
    - Español
  -
    - hr
    - hrvatski
  -
    - ja
    - 日本語
  -
    - ko
    - 한국어
  -
    - pt-BR
    - Português Brasileiro

# Plug-ins
gems:
  - jekyll-redirect-from

# Conversion
markdown: kramdown

# Outputting
permalink: pretty
timezone: GMT
